repos:
- repo: local
  hooks:
    - id: flake8 
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
    - id: isort 
      name: isort
      entry: poetry run isort -m 3 -tc -q
      language: system
      types: [python]
    - id: black 
      name: black
      entry: poetry run black -q
      language: system
      types: [python]
